name: SWCCore
version: ${project.version}
main: org.crewco.swccore.Startup
description: "A Template Plugin for 1.7.10"
authors:
  - "XST99"
depend: [Towny]

commands:
  reloadSwcConfig:
    description: Reload recipes command
    usage: /reloadconfig
  listdata:
    description: List Town Data
    usage: /listdata <nation>
  leadingNation:
    description: List Leading Nation Per world
    usage: /leadingNation
  claimResources:
    description: Claim the resources as the Nation Leader
    usage: /claimResources
  swcTownyUpdate:
    description: updates the plugin
  bounty:
    description: allows the player to set a bounty on another
  swcBountyUpdate:
    description: Allows an admin to update the plugin
  addon:
    description: Manage addons
    usage: /addon [list|reload|info] [addon-id]
    permission: yourplugin.addon
    permission-message: You don't have permission to manage addons